### ISSUE TITLE
Tables not enabled

### ISSUE THREAD

**Issue by devyntk** [firstwiki/wiki#3]
When trying to start the Kit of Parts page, I ran into the issue that markdown tables are not supported. It appears this a common issue with jekyll, described [here](http://stackoverflow.com/questions/16099153/table-not-render-when-use-redcarpet-in-jekyll-github-pages). It seems like an easy fix, but when inserting this into my local '_config.yml' file, it still did not work.  Is this an issue with my table (see below), or the server config?

`
| Item | Part Number | Qty | Rookie Tote Only? | Notes |
| --- | --- | --- | --- | --- |
| Throttle Motor | AE235100-0160 | 4 | No |   |
| Window Motor | 5-163800-RC1 | 2 | No |  |
`

EDIT: Just tried it inside an external markdown editor, and it rendered the table just fine. Is this intentional, and should we use HTML tables, or would we prefer to not use tables, period?

**Comment by virtuald** [comment]
Looks like [github pages only supports Kramdown](https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/) as a markdown processor. They [document tables](https://help.github.com/articles/organizing-information-with-tables/) too... which, yours works on my install of github pages/jekyll. Are you using the current version of the github-pages gem?

I added an example to the [style guide](http://firstwiki.github.io/docs/style-guide).

**Comment by virtuald** [comment]
It should be noted that the table styling is _terrible_... looks like that needs to be fixed. See http://stackoverflow.com/questions/24748389/jekyll-modify-the-way-some-html-tags-are-rendered for possible solutions if you're interested.

**Comment by virtuald** [comment]
Never mind, I fixed it, should look reasonable now.

**Comment by devyntk** [comment]
I just installed all of the gems today. It's running version 82 of github-pages. I've attached the entire file to see if it's something somewhere else in the file that's doing it.
[kit_of_parts copy.txt](https://github.com/firstwiki/wiki/files/310053/kit_of_parts.copy.txt)

**Comment by virtuald** [comment]
Heh, apparently kramdown is picky about spacing. If there's no newline between the heading and your table, then it's messed up. But if you put a newline in there, then it's fine and renders a table.
