### ISSUE TITLE
Detailed Game Manual Info?

### ISSUE THREAD

**Issue by devyntk** [firstwiki/wiki#31]
While working on the FIRST Stronghold page, I came upon an idea that may attract many more members; having a copy of all of the various rules of the game manual. Having an easy to use URL scheme (for example firstwiki.github.io/wiki/2017rules/G1) so it could be easily linked to in discussion. These pages could include history of the rule, discussion and criticisms of the rule, Q&A relevant to the rule and the such. It would be a significant amount of setup, particularly right after kickoff, but I think it could be a really usefully feature for the FRC community. Thoughts?

**Comment by virtuald** [comment]
I personally don't have the time to contribute to such a setup (too much RobotPy stuff to get done), but I won't stop you from doing it. If you're going to go through with it, I would recommend the following:

* Set up a different repository for this purpose (similar to how the wiki repo is separate from the frc teams repositories), as it's likely to generate a lot of pages over time
  * `/frcrules/2017/G1` would be how I would go about it...
  * I can set up the raw repo for it if you want
* Write a script that can parse the 2016 rules and generate the appropriate pages. Chances are the 2017 layout won't be that different, so you can work on this before kickoff and have it mostly done, and just have to tweak it a little to get the results you want on the day of kickoff
* Finally, check to see if FRC actually allows this. They may prohibit wholesale copying of the entirety of the rules, or the rules may need to fall under a different documentation license.

**Comment by devyntk** [comment]
I tried looking, but I can't find that the FRC manual is under any license at all. I have some free time today in the next few hours, so I'll look if I can't get this started.

**Comment by devyntk** [comment]
I got the "frcrules" repo started, runs fine locally. Some reason jekyll didn't like the collection name as a simple number, so I'm calling the repo the game title (stronghold instead of 2016). The URL is still just the number, so it should be fine. I tried to access it from the main site; is there something in a config somewhere that I need to change to add this?

**Comment by virtuald** [comment]
You need to create a gh-pages branch, and enable github pages for the repo.

**Comment by devyntk** [comment]
Always the stupid little mistakes. I've got about 15 game rules already added; it's very quick to add them in, I'm not sure it'll be worth it to write a script, especially with how funny the formatting gets with the blue boxes and images.

**Comment by devyntk** [comment]
Since this is implemented to the point that people can add game rules now, I'm going to close this issue.
