### ISSUE TITLE
Kit of Parts Page

### ISSUE THREAD

**Issue by maxnz** [firstwiki/wiki#53]
I am wondering if we want to add old KOP data to the KOP page in the form of links to archived versions in the wayback machine. If so, do we also want to add the current list in the form of a link or as a table like it currently is? Lastly, should the KOP page be a list of the KOP parts or a page about what the KOP is, was and how it has changed over time (or both)?

**Comment by virtuald** [comment]
>  a page about what the KOP is, was and how it has changed over time 

I suspect this makes the most sense and would be less effort.

**Comment by maxnz** [comment]
I have added the links to the 2016 KOP lists on the page, so should we delete the table?

**Comment by virtuald** [comment]
sure.

**Comment by maxnz** [comment]
Here: #57
